### ISSUE TITLE
Is the firmware real ?

### ISSUE THREAD

**Issue by Lothean** [Ch4rlus/ninebot_firmware#2]
I mean, the MCU has a read protection, right?
What's telling us it is legitimate and won't break the scooter when flashed?
Has the firmware been extracted from the Ninebot servers, where they store the updates, as the description of the repo could indicate?

**Comment by Ch4rlus** [comment]
The firmware has been extracted by using MITM during an update process with the official apk.

Theses are the legitimates firmwares of the scooter. However, I do not have tried flashing them.

**Comment by Lothean** [comment]
Thanks for the clarification!
